basePath: /
host: localhost:8080
info:
  contact:
    email: support@petmessenger.com
    name: API Support
    url: http://www.petmessenger.com/support
  description: This is the backend API for the Pet Messenger social app.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Pet Messenger API
  version: "1.0"
paths: {}
swagger: "2.0"
